### ISSUE TITLE
ncs-netsim delete-device feature was missing

### ISSUE THREAD

**Issue by kirankotari** [NSO-developer/cli-netsim-tool#1]
Hi Team, 

Is there any specific reason why the ncs-netsim delete-device feature is missing.

Thanks,
Kiran Kumar

**Comment by bicycleprincess** [comment]
I also want to know. 

Cheers,
Wei

**Comment by JohanVikman** [comment]
The cli-netsim-tool uses the ncs-netsim tool that is provided with NSO. The ncs-netsim tool does not have a delete-device function so therefore there is no delete-device function in this the cli-netsim-tool either.

The idea is to just remove the netsim network and start over if the need should arise.

**Comment by kirankotari** [comment]
This one has the feature https://github.com/NSO-developer/netsim-wrapper and more

**Comment by JohanVikman** [comment]
Yup, great work @kirankotari !
